/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./views/**/*.ejs", "./public/**/*.js"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#b51010",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-primary": "#08218a",
        error: "#ffb4ab",
        "inverse-surface": "#e5e2e1",
        "on-primary-fixed": "#00105c",
        "surface-bright": "#393939",
        "secondary-fixed": "#dee0ff",
        "tertiary-fixed": "#ffdad5",
        "on-tertiary": "#690002",
        "on-tertiary-container": "#ffc4bc",
        "surface-variant": "#353534",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-fixed": "#410001",
        secondary: "#bec4f2",
        "on-secondary-container": "#adb2df",
        "outline-variant": "#454652",
        "on-secondary-fixed": "#12183d",
        "surface-dim": "#131313",
        "surface-tint": "#bac3ff",
        "primary-container": "#3f51b5",
        "on-surface": "#e5e2e1",
        "on-secondary": "#272e53",
        "primary-fixed": "#dee0ff",
        "inverse-primary": "#4355b9",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "secondary-container": "#3e446b",
        "inverse-on-surface": "#313030",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#3e446b",
        "on-surface-variant": "#c5c5d4",
        "on-background": "#e5e2e1",
        "on-error": "#690005",
        "on-primary-container": "#cacfff",
        outline: "#8f909e",
        "on-tertiary-fixed-variant": "#930005",
        "surface-container-lowest": "#0e0e0e",
        surface: "#131313",
        "primary-fixed-dim": "#bac3ff",
        "surface-container": "#201f1f",
        "secondary-fixed-dim": "#bec4f2",
        "on-primary-fixed-variant": "#293ca0",
        background: "#131313",
        "surface-container-highest": "#353534",
        tertiary: "#ffb4a9",
        primary: "#bac3ff",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
